title: TechMCDocs
description: A new minecraft wiki, dedicated to only explaining game mechanics in an easy to edit format!

url: "techmcdocs.github.io"
plugins:
  - jekyll-sitemap

permalink: pretty
exclude:
  - README.md

keep_files: ["css","js"]

collections:
  basics:
    output: true
  tags:
    output: true
  filters:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: default
